### ISSUE TITLE
opensource.optum.com domain

### ISSUE THREAD

**Issue by JoshuaTheMiller** [Optum/optum.github.io#42]
The CNAME file must be created in the main branch under the [optumdocs directory](https://github.com/Optum/optum.github.io/tree/main/optumdocs), otherwise the changes will be lost the next time the [main build+release runs](https://github.com/Optum/optum.github.io/blob/main/.github/workflows/deploy.yml#L39 ).

![image](https://user-images.githubusercontent.com/4266541/149039802-6e50ed51-5d28-415c-831c-a2a417668d88.png)

## CNAME 

```
opensource.optum.com
```

**Comment by woodrbe** [comment]
Resolved with #44
